# Generated by Django 4.2.29 on 2026-03-21 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='case',
            name='ships',
            field=models.ManyToManyField(related_name='cases', to='boat.ship'),
        ),
    ]
