# Generated by Django 4.2.29 on 2026-03-21 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_ship_remove_case_description_remove_case_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keybind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
