# Generated by Django 4.2.29 on 2026-03-21 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_keybind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('boisium', models.IntegerField(default=0)),
                ('feronium', models.IntegerField(default=0)),
                ('charbonium', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('boat_level', models.IntegerField(default=1)),
                ('remaining_movement', models.IntegerField(default=0)),
                ('max_movement', models.IntegerField(default=15)),
            ],
        ),
    ]
