# Generated by Django 4.2.29 on 2026-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_currentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='direction',
            field=models.CharField(default='down', max_length=255),
        ),
    ]
