# Generated by Django 4.2.29 on 2026-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0005_currentstate_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
